included:

excluded:
- Carthage

disabled_rules:
- trailing_whitespace
- multiple_closures_with_trailing_closure

force_cast: warning

line_length: 250

identifier_name:
  min_length:
    error: 3
  excluded:
    - vc
    - id
    - in
    - ok
    - i

