name: PMS-iOS-V2

options:
  preGenCommand: fastlane pull
  postGenCommand: carting update # 생성 이후 명령 실행
  developmentLanguage: kr
  deploymentTarget:
    iOS: "11.0"
configs: # configuration 별 설정
    Debug: debug
    Release: release
configFiles:
    Debug: xcconfig/Project-Debug.xcconfig
    Release: xcconfig/Project-Release.xcconfig
  
settingGroups:
  app:
    DEVELOPMENT_TEAM: C2JSJLJ4FN
targets:
  PMS-iOS-V2:
    scheme:
      testTargets:
        - PMS-iOS-V2Tests
      environmentVariables:
        IMAGE_DIFF_DIR: $(SOURCE_ROOT)/$(PROJECT_NAME)Tests/FailureDiffs
        FB_REFERENCE_IMAGE_DIR: $(SOURCE_ROOT)/$(PROJECT_NAME)Tests/ReferenceImages
      language: Korean
      region: South Korea
    configFiles:
      Debug: xcconfig/PMS-iOS-V2-Debug.xcconfig
      Release: xcconfig/PMS-iOS-V2-Release.xcconfig
    sources:
      excludes:
          - "SceneDelegate.swift"
          - "Main.storyboard"
    settings:
      groups: [app]
      base:
        INFOPLIST_FILE: PMS-iOS-V2/Resource/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.dsm.pms-v2
        CURRENT_PROJECT_VERSION: 5
        VERSIONING_SYSTEM: Apple Generic
        CODE_SIGN_STYLE: Manual
        DEVELOPMENT_TEAM: Z25H7B85Z8
        CODE_SIGN_ENTITLEMENTS: PMS-iOS-V2/Resource/PMS-iOS-V2.entitlements
        FRAMEWORK_SEARCH_PATHS: $(inherited) $(PROJECT_DIR)/Carthage/Build $(PROJECT_DIR)/Carthage/Build/iOS
    postCompileScripts:
      - script: swiftlint
      - name: Swiftlint
    postBuildScripts:
      - script: |
            cp -r ${BUILT_PRODUCTS_DIR}/PMS.appex ${TARGET_BUILD_DIR}/${PLUGINS_FOLDER_PATH}/PMS.appex
      - name: Embed App Extensions

    dependencies:
      - target: PMS-Today-Extension
        codeSign: false
        embed: true
      - carthage: Carthage/Build/iOS/Alamofire
      - carthage: Carthage/Build/iOS/Differentiator
      - carthage: Carthage/Build/iOS/FSCalendar
      - carthage: Carthage/Build/iOS/Kingfisher
      - carthage: Carthage/Build/iOS/Lottie
      - carthage: Carthage/Build/iOS/Moya
      - carthage: Carthage/Build/iOS/Reachability
      - carthage: Carthage/Build/iOS/ReactiveSwift
      - carthage: Carthage/Build/iOS/RxBlocking
      - carthage: Carthage/Build/iOS/RxCocoa
      - carthage: Carthage/Build/iOS/RxDataSources
      - carthage: Carthage/Build/iOS/RxFlow
      - carthage: Carthage/Build/iOS/RxMoya
      - carthage: Carthage/Build/iOS/RxRelay
      - carthage: Carthage/Build/iOS/RxSwift
      - carthage: Carthage/Build/iOS/SkeletonView
      - carthage: Carthage/Build/iOS/SnapKit
      - carthage: Carthage/Build/iOS/Swinject
      - carthage: Carthage/Build/iOS/SwinjectAutoregistration
      - carthage: Carthage/Build/iOS/Then
      - carthage: Carthage/Build/iOS/FBLPromises
      - carthage: Carthage/Build/iOS/Promises
      - carthage: Carthage/Build/iOS/FBSDKCoreKit
      - carthage: Carthage/Build/iOS/FBSDKLoginKit
      - carthage: Carthage/Build/iOS/FBSDKGamingServicesKit
      - carthage: Carthage/Build/iOS/FBSDKShareKit
      - carthage: Carthage/Build/iOS/NaverThirdPartyLogin
      - carthage: Carthage/Build/iOS/KakaoOpenSDK
      - framework: Carthage/Build/FirebaseCrashlytics.xcframework
        embed: false
      - framework: Carthage/Build/FirebaseAnalytics.xcframework
        embed: false
      - framework: Carthage/Build/FirebaseMessaging.xcframework
        embed: false
      - framework: Carthage/Build/FirebaseABTesting.xcframework
        embed: false
      - framework: Carthage/Build/FirebaseCore.xcframework
        embed: false
      - framework: Carthage/Build/FirebaseCoreDiagnostics.xcframework
        embed: false
      - framework: Carthage/Build/FirebaseDynamicLinks.xcframework
        embed: false
      - framework: Carthage/Build/FirebaseInstallations.xcframework
        embed: false
      - framework: Carthage/Build/FirebasePerformance.xcframework
        embed: false
      - framework: Carthage/Build/FirebaseRemoteConfig.xcframework
        embed: false
      - framework: Carthage/Build/GoogleAppMeasurement.xcframework
        embed: false
      - framework: Carthage/Build/GoogleDataTransport.xcframework
        embed: false
      - framework: Carthage/Build/GoogleUtilities.xcframework
        embed: false
      - framework: Carthage/Build/nanopb.xcframework
        embed: false
      - framework: Carthage/Build/PromisesObjC.xcframework
        embed: false
      - framework: Carthage/Build/Protobuf.xcframework
        embed: false
    type: application
    platform: iOS
    sources: [PMS-iOS-V2]
    
  PMS-iOS-V2Tests:
    type: bundle.unit-test # 테스트 타입
    platform: iOS # 플랫폼
    sources: [PMS-iOS-V2Tests]
    configFiles:
      Debug: xcconfig/PMS-iOS-V2Tests-Debug.xcconfig
      Release: xcconfig/PMS-iOS-V2Tests-Release.xcconfig
    settings:
      groups: [app]
      INFOPLIST_FILE: Resource/Info.plist # Info.plist 등록
      commandLineArguments: [test: true]
      FRAMEWORK_SEARCH_PATHS: $(inherited) $(PROJECT_DIR)/Carthage/Build/iOS
    preBuildScripts:
      - path: PMS-iOS-V2Tests/Resource/script.sh
        name: Carthage
        inputFileLists:
          - $(SRCROOT)/PMS-iOS-V2Tests/Resource/PMS-iOS-V2-inputPaths.xcfilelist
    dependencies:
      - carthage: FBSnapshotTestCase
        embed: false
      - carthage: RxTest
        embed: false
      - carthage: RxSwift
        embed: false
  PMS-iOS-V2UITests:
    type: bundle.ui-testing # 테스트 타입
    platform: iOS # 플랫폼
    sources: [PMS-iOS-V2UITests]
    configFiles:
      Debug: xcconfig/PMS-iOS-V2UITests-Debug.xcconfig
      Release: xcconfig/PMS-iOS-V2UITests-Release.xcconfig
    settings:
      groups: [app]
      INFOPLIST_FILE: Resource/Info.plist # Info.plist 등록
      commandLineArguments: [test: true]
      FRAMEWORK_SEARCH_PATHS: $(inherited)

  PMS-Today-Extension:
    type: app-extension
    platform: iOS
    sources: [PMS-Today-Extension, PMS-iOS-V2/Extension/Colors+Generated.swift, PMS-iOS-V2/Localize/LocalizedString.swift, PMS-iOS-V2/Domain/Entity/Calendar/PMSCalendar.swift, PMS-iOS-V2/Resource/Colors.xcassets]
    configFiles:
      Debug: xcconfig/PMS-Today-Extension-Debug.xcconfig
      Release: xcconfig/PMS-Today-Extension-Release.xcconfig
    settings:
      base:
        INFOPLIST_FILE: PMS-Today-Extension/Resource/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.dsm.pms-v2.PMS-TodayExtension
        CODE_SIGN_STYLE: Manual
        DEVELOPMENT_TEAM: Z25H7B85Z8
        FRAMEWORK_SEARCH_PATHS: $(inherited) $(PROJECT_DIR)/Carthage/Build/iOS
    preBuildScripts:
      - path: PMS-iOS-V2Tests/Resource/script.sh
        name: Carthage
        inputFileLists:
          - $(SRCROOT)/PMS-Today-Extension/Resource/PMS-Today-Extension-inputPaths.xcfilelist
    dependencies:
      - sdk: NotificationCenter.framework
      - carthage: Carthage/Build/iOS/FSCalendar
      - carthage: Carthage/Build/iOS/Alamofire
