# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :push do
    rome(
    command: "upload",
    platform: "iOS",
    concurrently: "true",
    )
     sh("cd ..;carting update")
  end

  lane :pull do
    rome(
      command: "download",
      platform: "iOS",
      concurrently: "true"
    )
    sh("cd ..;punic download")
  end

  lane :test do
    run_tests(
      buildlog_path: "./fastlane/fastlane-buildlog",
      derived_data_path: "~/Library/Developer/Xcode/DerivedData",
      workspace: "PMS-iOS-V2.xcodeproj",
      scheme: "PMS-iOS-V2Tests")
  end

  lane :github do
    get_certificates(
      development: false
    )
    create_keychain(
      name: "ios_app_store",
      password: "1234",
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      add_to_search_list: true,
    )
    match(type: "appstore", readonly: true, keychain_name: 'ios_app_store', keychain_password: '1234')
    increment_build_number
    build_app(project: "PMS-iOS-V2.xcodeproj", scheme: "PMS-iOS-V2")
    upload_to_app_store(
      force: true,
      skip_metadata: true,
      skip_screenshots: true,
      skip_binary_upload: false,
      app_identifier: "com.dsm.pms-v2",
      automatic_release: false,
      submit_for_review: false,
      submission_information: {
        add_id_info_serves_ads: false,
        add_id_info_tracks_action: false,
        add_id_info_tracks_install: true,
        add_id_info_uses_idfa: true,
        content_rights_has_rights: true,
        content_rights_contains_third_party_content: true,
        export_compliance_platform: 'ios',
        export_compliance_compliance_required: false,
        export_compliance_encryption_updated: false,
        export_compliance_app_type: nil,
        export_compliance_uses_encryption: false,
        export_compliance_is_exempt: false,
        export_compliance_contains_third_party_cryptography: false,
        export_compliance_contains_proprietary_cryptography: false,
        export_compliance_available_on_french_store: false
      }
    )
    upload_to_testflight
  end

  lane :screenshots do 
    capture_screenshots(
	reinstall_app: true,
	clean: true)
  end
end