name: Publish iOS App to App Store

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  release-ios:
    name: Build and release iOS app
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: submodules-init
        uses: snickerbockers/submodules-init@v4
      - name: Bundle Install
        run: bundle install
      - name: Rome Install
        run: |
          brew tap tmspzz/tap https://github.com/tmspzz/homebrew-tap.git
          brew install tmspzz/homebrew-tap/rome
      - name: Set Appstore Connect User
        run: bundle exec fastlane fastlane-credentials add --username ${{ secrets.APPLE_ACCOUNT }} --password ${{ secrets.FASTLANE_PASSWORD }}
      - name: Set AWS Config
        uses: aws-actions/configure-aws-credentials@v1
      - name: Deploy App
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
        env:
          MATCH_REPO: ${{ secrets.MATCH_REPO }}
          APPLE_ACCOUNT: ${{ secrets.APPLE_ACCOUNT }}
          TEAM_ID: ${{ secrets.TEAM_ID }}
          ITC_TEAM_ID: ${{ secrets.ITC_TEAM_ID }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          FASTLANE_SESSION: ${{ secrets.TOKEN }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
        run: bundle exec fastlane github
